apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-k8s-aws
  namespace: quarkus-k8s
  labels:
    app: quarkus-k8s-aws
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quarkus-k8s-aws
  template:
    metadata:
      labels:
        app: quarkus-k8s-aws
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
      containers:
        - name: quarkus-k8s-aws
          image: duduxs/quarkus-k8s-aws
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - name: http
              containerPort: 8080
          imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: quarkus-k8s-aws
  namespace: quarkus-k8s
  labels:
    app: quarkus-k8s-aws
spec:
  type: LoadBalancer
  selector:
    app: quarkus-k8s-aws
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
