apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-k8s-aws
spec:
  selector:
    matchLabels:
      app: quarkus-k8s-aws
  template:
    metadata:
      labels:
        app: quarkus-k8s-aws
    spec:
      containers:
      - name: quarkus-k8s-aws
        image: duduxs/quarkus-k8s-aws
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: quarkus-k8s-aws-service
spec:
  type: LoadBalancer
  selector:
    app: quarkus-k8s-aws
  ports:
  - port: 8090
    targetPort: 8080

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: quarkus-k8s-aws-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: quarkus-k8s-aws
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
